"""team

Revision ID: 644a779f47a7
Revises: 545ddafbb75a
Create Date: 2018-08-23 21:28:22.878182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '644a779f47a7'
down_revision = '545ddafbb75a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('team', sa.String(), nullable=True))
    op.create_foreign_key(None, 'user', 'team', ['team'], ['team'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'team')
    # ### end Alembic commands ###
