"""project table

Revision ID: 68567d7c3750
Revises: 1d97fdbd67e8
Create Date: 2018-08-09 05:58:12.000111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68567d7c3750'
down_revision = '1d97fdbd67e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('project', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('project')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project')
    # ### end Alembic commands ###
