"""empty message

Revision ID: 98b5f301db7a
Revises: 561d96c0cd64
Create Date: 2018-07-30 21:03:55.170006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98b5f301db7a'
down_revision = '561d96c0cd64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('minicard', sa.Column('date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('minicard', 'date')
    # ### end Alembic commands ###
