"""minicard table

Revision ID: 561d96c0cd64
Revises: b4a6c90556d4
Create Date: 2018-07-29 20:54:39.948373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '561d96c0cd64'
down_revision = 'b4a6c90556d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('minicard',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('project', sa.String(length=64), nullable=True),
    sa.Column('task', sa.String(length=64), nullable=True),
    sa.Column('predicted_hrs', sa.Numeric(), nullable=True),
    sa.Column('actual_hrs', sa.Numeric(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('minicard')
    # ### end Alembic commands ###
