"""subtask

Revision ID: ba8a40d8be23
Revises: 93c9e1721c4b
Create Date: 2018-08-26 23:36:23.971251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba8a40d8be23'
down_revision = '93c9e1721c4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('minicard', sa.Column('subtask', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('minicard', 'subtask')
    # ### end Alembic commands ###
